
[package]
authors = ["APIx DevTools team"]
edition = "2021"
name = "atlas_local"
version = "0.0.0-preview.2"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.99"
atlas-local = { git = "https://github.com/mongodb/atlas-local-lib.git", rev = "fa7cb7aa67e9169f48864a81f3b63f1cf35c81bb" }
bollard = "0.19.2"
napi = { version = "3.0.0", features = ["async", "anyhow"] }
napi-derive = "3.0.0"
semver = "1.0.26"

[build-dependencies]
napi-build = "2"

[profile.release]
lto = true
strip = "symbols"
