
[package]
authors = ["APIx DevTools team"]
edition = "2021"
name = "atlas_local"
version = "1.0.2"
license = "Apache-2.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.99"
atlas-local = { git = "https://github.com/mongodb/atlas-local-lib.git", rev = "9b582845ebf2e4ca4f6543fa5bb1262920e2fbe6" }
bollard = "0.19.4"
napi = { version = "^3.5.2", features = ["async", "anyhow"] }
napi-derive = "^3.3.3"
semver = "1.0.26"

[build-dependencies]
napi-build = "2"

[profile.release]
lto = true
strip = "symbols"
