
[package]
authors = ["APIx DevTools team"]
edition = "2021"
name = "atlas_local"
version = "0.0.0-preview.9"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.99"
atlas-local = { git = "https://github.com/mongodb/atlas-local-lib.git", rev = "532d5f3c52788cb14f746e7b10edb3ce33dad89e" }
bollard = "0.19.2"
napi = { version = "^3.3.0", features = ["async", "anyhow"] }
napi-derive = "^3.2.5"
semver = "1.0.26"

[build-dependencies]
napi-build = "2"

[profile.release]
lto = true
strip = "symbols"
