
[package]
authors = ["APIx DevTools team"]
edition = "2021"
name = "atlas_local"
version = "1.1.0"
license = "Apache-2.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.99"
atlas-local = { version = "0.2.0", default-features = false }
bollard = "0.19.4"
napi = { version = "^3.7.1", features = ["async", "anyhow"] }
napi-derive = "^3.4.1"
semver = "1.0.26"

[build-dependencies]
napi-build = "2"

[profile.release]
lto = true
strip = "symbols"
